import Head from 'next/head'
import { Ubuntu } from 'next/font/google'
import styled from 'styled-components'
import { HeroBg } from '@/components/Hero/HeroBg'
import { Content } from '@/components/Content/Content'
import { useSteps } from '@/hooks/use-steps'
import { useState } from 'react'
import { PersonalData } from '@/components/Content/StepsForm/PersonalData/PersonalData'
import { SubscriptionPlan } from '@/components/Content/StepsForm/SubscriptionPlan/SubscriptionPlan'

const ubuntu = Ubuntu({ subsets: ['latin'], weight: ['300', '500', '700'] })

const Main = styled.main`
	width: min(100%, 800px);
`
type FormData = {
	email: string
	name: string
	phone: string
	firstStepValid: boolean
	selectedPlanPrice: number
	thisTarget: string | null
	secondStepIsValid: boolean
}
const INITIAL_DATA: FormData = {
	email: '',
	name: '',
	phone: '',
	firstStepValid: false,
	selectedPlanPrice: 9,
	thisTarget: '',
	secondStepIsValid: false,
}

export default function Home() {
	const [data, setData] = useState(INITIAL_DATA)

	const updateFields = (fields: Partial<FormData>) => {
		setData(prev => {
			return { ...prev, ...fields }
		})
	}
	const { nextStep, backStep, step, currentStepIndex, isLastStep, isFirstStep } = useSteps([
		<PersonalData
			key={1}
			phone={data.phone}
			email={data.email}
			name={data.name}
			updateFields={updateFields}
		/>,
		<SubscriptionPlan
			thisTarget={data.thisTarget}
			secondStepIsValid={data.secondStepIsValid}
			key={2}
			updateFields={updateFields}
		/>,
		<div key={3}>three</div>,
		<div key={4}>four</div>,
	])
	console.log(data)
	return (
		<>
			<Head>
				<title>Form</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<Main className={ubuntu.className}>
				<HeroBg />
				<Content
					firstStepIsValid={data.firstStepValid}
					isLastStep={isLastStep}
					isFirstStep={isFirstStep}
					step={step}
					back={backStep}
					next={nextStep}
				/>
			</Main>
		</>
	)
}
