import Head from 'next/head'
import { Ubuntu } from 'next/font/google'
import styled from 'styled-components'
import { HeroBg } from '@/components/Hero/HeroBg'
import { Content } from '@/components/Content/Content'
import { useSteps } from '@/hooks/use-steps'
import { useState } from 'react'
import { PersonalData } from '@/components/Content/StepsForm/PersonalData/PersonalData'
import { SubscriptionPlan } from '@/components/Content/StepsForm/SubscriptionPlan/SubscriptionPlan'
import { Enhances } from '@/components/Content/StepsForm/Enhances/Enhances'
import { Summary } from '@/components/Content/StepsForm/Summary/Summary'
import { Confirmation } from '@/components/Content/StepsForm/Confirmation/Confirmation'
const ubuntu = Ubuntu({ subsets: ['latin'], weight: ['300', '500', '700'] })

const Main = styled.main`
	width: 100%;

	@media (min-width: 768px) {
		position: relative;
		display: flex;
		gap: 3.5rem;
		background-color: #fff;
		border-radius: 10px;
		padding: 0.8rem;
		height: 500px;
	}
`
type FormData = {
	firstStepValid: boolean
	toggleStatePlans: boolean
	goBackToPlans: boolean
	selectedPlanPrice: number
	onlineServicePrice: number
	largerStoragePrice: number
	customProfilePrice: number
	email: string
	name: string
	phone: string
	selectedPlan: string
	choosedPlan: string
	onlineService: string
	largerStorage: string
	customProfile: string
}

const INITIAL_DATA: FormData = {
	email: '',
	name: '',
	phone: '',
	firstStepValid: false,
	selectedPlanPrice: 9,
	selectedPlan: '1',
	choosedPlan: 'Arcade',
	goBackToPlans: false,
	toggleStatePlans: false,
	onlineService: '',
	largerStorage: '',
	customProfile: '',
	onlineServicePrice: 0,
	largerStoragePrice: 0,
	customProfilePrice: 0,
}

export default function Home() {
	const [data, setData] = useState(INITIAL_DATA)
	const updateFields = (fields: Partial<FormData>) => {
		setData(prev => {
			return { ...prev, ...fields }
		})
	}
	const { nextStep, backStep, currentStepIndex, step, isLastStep, isFirstStep } = useSteps(
		[
			<PersonalData
				key={1}
				phone={data.phone}
				email={data.email}
				name={data.name}
				updateFields={updateFields}
			/>,
			<SubscriptionPlan
				key={2}
				selectedPlan={data.selectedPlan}
				updateFields={updateFields}
				toggleStatePlans={data.toggleStatePlans}
			/>,
			<Enhances
				key={3}
				onlineService={data.onlineService}
				toggleStatePlans={data.toggleStatePlans}
				largerStorage={data.largerStorage}
				customProfile={data.customProfile}
				updateFields={updateFields}
			/>,
			<Summary
				key={4}
				choosedPlan={data.choosedPlan}
				togglePlan={data.toggleStatePlans}
				updateFields={updateFields}
				customProfilePrice={data.customProfilePrice}
				largerStoragePrice={data.largerStoragePrice}
				onlineServicePrice={data.onlineServicePrice}
				selectedPlanPrice={data.selectedPlanPrice}
			/>,
			<Confirmation key={5} />,
		],
		data.goBackToPlans
	)

	return (
		<>
			<Head>
				<title>Form</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<Main className={ubuntu.className}>
				<HeroBg currentIndex={currentStepIndex} />
				<Content
					currentStepIndex={currentStepIndex}
					firstStepIsValid={data.firstStepValid}
					isLastStep={isLastStep}
					isFirstStep={isFirstStep}
					step={step}
					back={backStep}
					next={nextStep}
				/>
			</Main>
		</>
	)
}
